# This file is designed for production server deployment, not local development work
# For a containerized local dev environment, see: https://github.com/mastodon/mastodon/blob/main/docs/DEVELOPMENT.md#docker
version: '3.8'
services:
  web:
    build:
      context: .
    image: bubbles:latest
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  streaming:
    build:
      context: .
    image: bubbles:latest
    command: bundle exec node ./streaming
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    build:
      context: .
    image: bubbles:latest
    command: bundle exec sidekiq
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: mastodon
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: mastodon_production
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6

volumes:
  db-data:

